routes/web.php
<?php

use App\Http\Controllers\FaqController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/page1', function () {
    return view('principal');
});
Route::get('/page2', function () {
    $user=App\Models\users::find(2);
    return dd($user->username);
});
Route::get('/page3', function () {
    return view('third');
})->middleware('auth');
Route::get('/optionalParam/{optional?}', function ($optional='es OPCIONAL') {
   
    return 'la ruta tiene el parametro NO requerido '.$optional;
})->middleware('auth');

Route::resource('faqs','App\Http\Controllers\FaqController');
Route::post('/search_faqs',[App\Http\Controllers\FaqController::class, 'search']);

Route::resource('tags','App\Http\Controllers\TaqController');
Route::post('/search_tags',[App\Http\Controllers\TaqController::class, 'search']);

Route::resource('artists','App\Http\Controllers\ArtistController');
Route::post('/search_artists',[App\Http\Controllers\ArtistController::class, 'search']);

Route::resource('users','App\Http\Controllers\UsersController');
Route::post('/search_users',[App\Http\Controllers\UsersController::class, 'search']);

Route::get('songs/{id}',[App\Http\Controllers\SongController::class, 'index'])->middleware('auth');
Route::post('/search/{id}',[App\Http\Controllers\SongController::class, 'search']);

Route::resource('user_songs','App\Http\Controllers\UserSongController')->middleware('auth');
Route::post('/search_user_songs',[App\Http\Controllers\UserSongController::class, 'search']);

Route::resource('users/{id}/song','App\Http\Controllers\ListSongController')->middleware('auth');
Route::post('/search_songs/{id}',[App\Http\Controllers\ListSongController::class, 'search']);

Route::resource('mails','App\Http\Controllers\MailController');
Route::get('changes_password','App\Http\Controllers\AccountsController@indexPasswordRequest');
Route::post('reset_password_with_token', 'App\Http\Controllers\AccountsController@validatePasswordRequest');
Route::post('update_password','App\Http\Controllers\AccountsController@resetPassword');

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/crud-tag/tag-create.blade.php
@extends('templates.template-base')
@section('sub-menu')
    <h2>CREATE TAG</h2>
    <ol class="breadcrumb">
       
        <li class="active">
            <strong>New Tag<</strong>
        </li>
    </ol>
    </div>
@endsection

@section('content')
<div class="row">
  <div class="col-lg-12">
      <div class="ibox float-e-margins">
          <div class="ibox-title">
              <h5>form to Create new Tag<small>Practica de laravel</small></h5>
          </div>
          <div class="ibox-content">
              <form class="form-horizontal" method="POST" action="../tags">
                  @csrf          
                  <div class="form-group">
                      <label class="col-sm-2 control-label">Name Tag</label>
                      <div class="col-sm-10">
                          <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" >
                      </div>
                  </div>
                  @error('name')
                      <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  <div class="hr-line-dashed"></div>

                  <div class="form-group">
                      <label class="col-sm-2 control-label">Date Time</label>
                      <div class="col-sm-10 d-flex">
                        <div class="row">
                          <div class="col-md-3">
                            <div class="input-group date">
                              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                              <input id="date_added" type="text" class="form-control @error('create-date') is-invalid @enderror" value="03/04/2014" name="create-date">
            
                            </div>
                          </div>
                          <div class="col-md-2">
                            <input class="form-control @error('time') is-invalid @enderror" type="time" value="13:45:00" id="example-time-input" name="time">
                          </div>
                        </div>
                      </div>                           
                  </div>
                  @error('create-date')
                    <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  @error('time')
                    <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  <div class="hr-line-dashed"></div>
                  
                  <div class="form-group">
                      <div class="col-sm-4 col-sm-offset-2">
                          <a href="../tags" class="btn btn-white">Cancel</a>
                          <button class="btn btn-primary" type="submit">Save changes</button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
  </div>
</div>

  @endsection

resources/views/crud-tag/tag-edit.blade.php
@extends('templates.template-base')
@section('sub-menu')
    <h2>EDIT TAG</h2>
    <ol class="breadcrumb">
    
       
        <li class="active">
            <strong>update TAG</strong>
        </li>
    </ol>
    </div>
@endsection

@section('content')




<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>form to Create new Tag<small>Practica de laravel</small></h5>
            </div>
            <div class="ibox-content">
                <form class="form-horizontal" method="POST" action="../{{ $tag->id }}">
                    @csrf
                    @method('PUT')     
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Name Tag</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $tag->name }}">
                        </div>
                    </div>
                    @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <div class="hr-line-dashed"></div>
  
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Data time</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control @error('data-time') is-invalid @enderror" name="data-time"  value="{{  $tag->create_date_time }}">
                        </div>
                    </div>
                    @error('data-time')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <div class="hr-line-dashed"></div>
                    
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <a href="../../tags" class="btn btn-white">Cancel</a>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
  </div>

  @endsection

resources/views/crud-tag/tag-principal.blade.php
@extends('templates.template-base')
@section('sub-menu')
    <h2>TAGS</h2>
    <ol class="breadcrumb">
        <li>
            <a href="index.html">List Tag</a>
        </li>
        <li class="active">
            <strong>TAGS</strong>
        </li>
    </ol>
    </div>
@endsection
@section('content')




<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of Artist</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-plus"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li> <a href="./tags/create" > create new Tag</a>
                            </li>
                        </ul>
                    </div>
                    @if(Session::has('store'))
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <a class="alert-link" href="#">{{Session::get('store')}} </a> successfully saved! .
                        </div>                    
                    @endif
                    @if(Session::has('update'))                    
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <a class="alert-link" href="#">{{Session::get('update')}} </a> successfully updated! .
                        </div>                   
                    @endif
                    @if(Session::has('delete'))                   
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <a class="alert-link" href="#">{{Session::get('delete')}} </a>  deleted correctly! .
                        </div>                                         
                    @endif
                </div>
               
                <div class="ibox-content">

                    <table class="footable table table-stripped toggle-arrow-tiny">
                        <div class="col-sm-3">
                            <form action="/search_tags" method="POST" role="search">
                                @csrf
                                <div class="input-group">
                                    <input type="text" placeholder="Search" class="input-sm form-control" name="search"> 
                                    <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary"> Go!</button> </span>
                                </div>
                            </form>
                        </div>
                        <thead>
                        <tr>
                            <th data-toggle="true">#</th>
                            <th >Name</th>
                            <th>date create</th>
                            <th>update date </th>
                            <th>Action</th>
                            
                        </tr>
                        </thead>
                        <tbody>
                            @foreach ($tags as $tag)
                                <tr>
                                    <td>{{ $loop->index+1 }}</td>
                                    <td>{{ $tag->name}}</td>
                                    <td>{{ $tag->create_date_time}}</td>
                                    <td>{{ $tag->updated_date_time}}</td>
                                    <td><a href="./tags/{{ $tag->id }}/edit"><i class="fa fa-pencil-square-o"> update</i></a>
                                        
                                        <form method="POST" action="{{ route('tags.destroy',$tag->id) }}">
                                            @csrf
                                        @method('DELETE')
                                        
                                            <button type="submit"  class="fa fa-trash" style="color: red;margin-top:10px;border:none;background-color: transparent;">delete</button>
                                        </form>
                                        
                                        </td>
                                   
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot style="display: none">
                        <tr>
                            <td colspan="5">
                                <ul class="pagination pull-right"></ul>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                    {{ $tags->links() }}
                </div>
            </div>
        </div>
    </div>
</div>   

@endsection