routes/web.php
<?php

use App\Http\Controllers\FaqController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/page1', function () {
    return view('principal');
});
Route::get('/page2', function () {
    $user=App\Models\users::find(2);
    return dd($user->username);
});
Route::get('/page3', function () {
    return view('third');
})->middleware('auth');
Route::get('/optionalParam/{optional?}', function ($optional='es OPCIONAL') {
   
    return 'la ruta tiene el parametro NO requerido '.$optional;
})->middleware('auth');

Route::resource('faqs','App\Http\Controllers\FaqController');
Route::post('/search_faqs',[App\Http\Controllers\FaqController::class, 'search']);

Route::resource('tags','App\Http\Controllers\TaqController');
Route::post('/search_tags',[App\Http\Controllers\TaqController::class, 'search']);

Route::resource('artists','App\Http\Controllers\ArtistController');
Route::post('/search_artists',[App\Http\Controllers\ArtistController::class, 'search']);

Route::resource('users','App\Http\Controllers\UsersController');
Route::post('/search_users',[App\Http\Controllers\UsersController::class, 'search']);

Route::get('songs/{id}',[App\Http\Controllers\SongController::class, 'index'])->middleware('auth');
Route::post('/search/{id}',[App\Http\Controllers\SongController::class, 'search']);

Route::resource('user_songs','App\Http\Controllers\UserSongController')->middleware('auth');
Route::post('/search_user_songs',[App\Http\Controllers\UserSongController::class, 'search']);

Route::resource('users/{id}/song','App\Http\Controllers\ListSongController')->middleware('auth');
Route::post('/search_songs/{id}',[App\Http\Controllers\ListSongController::class, 'search']);

Route::resource('mails','App\Http\Controllers\MailController');
Route::get('changes_password','App\Http\Controllers\AccountsController@indexPasswordRequest');
Route::post('reset_password_with_token', 'App\Http\Controllers\AccountsController@validatePasswordRequest');
Route::post('update_password','App\Http\Controllers\AccountsController@resetPassword');

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/users.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class users extends Authenticatable
{
    use HasFactory, Notifiable;
    protected $table='users';
    protected $fillable =[
        'username',
        'profile_picture',
        'email',
        'password',
        'mobile_number',
        'fb_id',
        'user_role',
        'access_token',
        'device_token',
    ];
    //use HasFactory;
    public function userSongs()
    {
        return $this->hasMany(UserSong::class,'user_id');
    }
    public function songs(){
        return $this->belongsToMany(Song::class, 'user_song', 'user_id', 'song_id');
    }
    public function scopeSearchSong($query,$search){
        return $this->belongsToMany(Song::searchSong($search), 'user_song', 'user_id', 'song_id');//->where('name', 'LIKE', "%$search%")->orWhere('id', 'LIKE', "%$search%")->orWhere('year', 'LIKE', "%$search%");
    }
   public function scopeFindEmail($query, $email){
       return $query->where('email','=',$email);
   }
   public function scopeInnerJoinUser($query,$table_join){
    return $query->join($table_join, 'users.id','=',"$table_join.user_id");
   }
   
   public function getNameUserAttribute($value){
    return $this->attributes['username']=strtoupper($value);
   }
   public function getUsernameAttribute($value)
    {
        return ucfirst($value);
    }
    public function scopeSearchUsers($query,$search)
    {
        return $query->where('username', 'LIKE', "%$search%")->orWhere('id', 'LIKE', "%$search%")->orWhere('email', 'LIKE', "%$search%")->orWhere('mobile_number', 'LIKE', "%$search%")->orWhere('fb_id', 'LIKE', "%$search%")->orWhere('user_role', 'LIKE', "%$search%");
    }
}

app/Http/Controllers/Api/v1/UserController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use App\Http\Resources\UserResource;
use App\LoadImage\Img;
use App\Models\users;
use Illuminate\Contracts\Validation\Validator as ValidationValidator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationData;
use Illuminate\Validation\Validator as IlluminateValidationValidator;
use Symfony\Component\VarDumper\VarDumper;

class UserController extends Controller
{
    public function login(Request $request){
        $validation= $this->verificationEmail($request);
        if($validation==false){    
            return response()->json(['data'=>'verifica los datos que ingresaste sean correctos'],400);
        }

        if (Auth::attempt($request->all())) {
            $user = Auth::user();
            $this->generateToken($user);
            return response()->json(['data'=>new UserResource($user)]);
        }

        return response()->json(['data'=>'el usuario ingresado no existe'],400);
    }

    public function verificationEmail(Request $request){
        $validator = Validator::make($request->all(),[
            'email'    => 'required|string|email',
            'password' => 'required|string'
            ]);

        if ($validator->fails()) {
            return false;
        }
        return true;
    }

    public function generateToken($user)
    {
        $user->api_token = Str::random(60);
        $user->save();
        return $user->api_token;
    }

    public function update(Request $request)
    {   
        //verifiqued la validacion
        $validation= $this->verificationUser($request);
        if($validation==false){    
            return response()->json(['data'=>'verifica que los datos cumplan con los requisitos'],400);
        }
        //update user
        $user = users::find($request->id);
        $fields=$request->all();
        $fields['profile_picture']=Img::update($request,'profile_picture',$user);
        $user->update($fields);

        return response()->json(['data'=>new UserResource($user)], 200);
    }

    private function verificationUser(Request $request){
        $validator = Validator::make($request->all(),[
            'name' => 'required|string',
            'profile_picture' => 'required',
            'email' => 'required|email',
            'password' => 'required|string|min:8',
            'mobile_number' => 'required|min:7|max:9',
            'rol_user' => 'required|string',
            ]);

        if ($validator->fails()) {
            return false;
        }
        return true;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\users;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use League\CommonMark\Extension\Attributes\Node\Attributes;
use App\loadImage;
use App\LoadImage\Img;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        
        $users=users::paginate(5);
        $user_auth=auth()->user()->id;
        
        return view('users/users-view')->with('users',$users)->with('user_auth',$user_auth);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
   /* public function create()
    {
        //
    }
*/
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $user=users::find($id);
        $user_auth=auth()->user()->id;
        return view('users/user-edit')->with('user',$user)->with('user_auth',$user_auth);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
            'profile_picture' => 'required',
            'email' => 'required|email',
            'password' => 'required|string|min:8',
            'mobile_number' => 'required|min:7|max:9',
            'rol_user' => 'required|alpha',
        ],['email.unique'=>'el email '.$request->get('email').' ya ah sido registrado']);
        //update user
        $user=users::find($id);
        $user->username=$request->get('name');
        Img::update($request,'profile_picture',$user);
        $user->email=$request->get('email');
        $user->password=Hash::make($request->get('password'));
        $user->mobile_number=$request->get('mobile_number');
        $user->user_role=$request->get('rol_user');
        $user->save();
        $request->session()->flash('update', "$user->username");
        return redirect('users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=users::find($id);
        Storage::delete('public/',$user->profile_picture);
        $user->delete();
        return redirect('./users')->with('delete',$user->username);
    }

    public function search(Request $request){
        $users=users::searchUsers($request->search)->paginate(5);
        $user_auth=auth()->user()->id;
        return view('users/users-view')->with('users',$users)->with('user_auth',$user_auth);    
    }
}

resources/views/users/user-edit.blade.php
@extends('layouts.app')
@section('head')
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
@endsection
@section('nav')
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ $user->username }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                                <a class="dropdown-item" href="../../home">cancel</a>
                                
                            </div>

                        </li>
                    
                </ul>
            </div>
        </div>
    </nav>   
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" action="../{{ $user->id }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                       
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->username}}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __(' New Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="profile-picture" class="col-md-4 col-form-label text-md-right">{{ __('Profile picture') }}</label>

                            <div class="col-md-6">
                                <input id="profile_picture" type="file" class="form-control @error('profile_picture') is-invalid @enderror" name="profile_picture" required>
                                @error('profile_picture')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="mobile-number" class="col-md-4 col-form-label text-md-right">{{ __('mobile number') }}</label>

                            <div class="col-md-6">
                                <input id="mobile_number" type="number" class="form-control @error('mobile_number') is-invalid @enderror" name="mobile_number" value="{{ $user->mobile_number }}" required>
                                @error('mobile_number')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="rol-user" class="col-md-4 col-form-label text-md-right">{{ __('User Rol ') }}</label>

                            <div class="col-md-6">
                                <input id="rol_user" type="text" class="form-control @error('rol_user') is-invalid @enderror" name="rol_user" value="{{ $user->user_role }}" required>
                                @error('rol_user')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/users-view.blade.php
@extends('templates.template-base')
@section('sub-menu')
    <h2>USERS</h2>
    <ol class="breadcrumb">
        <li>
            <a>List Users</a>
        </li>
        <li class="active">
            <strong>Users</strong>
        </li>
    </ol>
    </div>
@endsection
@section('content')

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of User</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-plus"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li> <a href="./register" > create new artist</a>
                            </li>
                        </ul>
                    </div>
                   
                    @if(Session::has('update'))                    
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <a class="alert-link" href="#">{{Session::get('update')}} </a> successfully updated! .
                        </div>                   
                    @endif
                    @if(Session::has('delete'))                   
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <a class="alert-link" href="#">{{Session::get('delete')}} </a>  deleted correctly! .
                        </div>                                         
                    @endif
                </div>
                <div class="ibox-content">

                    <table class="footable table table-stripped toggle-arrow-tiny">
                        <thead>
                        <tr>
                            <th data-toggle="true">#</th>
                            <th >Username</th>
                            <th>email</th>
                            <th>mobile_number</th>
                            <th>user_role</th> 
                            <th>Action</th>
                            <th data-hide="all">perfile image</th>
                        </tr>
                        </thead>
                        <tbody>
                            <div class="col-sm-3">
                                <form action="/search_users" method="POST" role="search">
                                    @csrf
                                    <div class="input-group">
                                        <input type="text" placeholder="Search" class="input-sm form-control" name="search"> 
                                        <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary"> Go!</button> </span>
                                    </div>
                                </form>
                            </div>
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{ $loop->index+1 }}</td>
                                    <td>{{ $user->username}}</td>
                                    <td>{{ $user->email}}</td>
                                    <td>{{ $user->mobile_number}}</td>
                                    <td>{{ $user->user_role}}</td>
                                    <td><a href="./users/{{ $user->id }}/edit"><i class="fa fa-pencil-square-o"> update</i></a>
                                        <div style="margin-top:10px"><a href="./users/{{ $user->id }}/song" style="color: rgb(34, 155, 94)"><i class="fa fa-eye"> view song</i></a></div>
                                        <form method="POST" action="{{ route('users.destroy',$user->id) }}">
                                            @csrf
                                        @method('DELETE')
                                        
                                            <button type="submit"  class="fa fa-trash" style="color: red;margin-top:10px;border:none;background-color: transparent;">delete</button>
                                        </form>
                                        
                                        </td>
                                    <td><img src="{{ asset('storage').'/'.$user->profile_picture }}" alt="" width="200"></td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot style="display: none">
                        <tr>
                            <td colspan="5">
                                <ul class="pagination pull-right"></ul>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>
</div>   
    
@endsection