routes/web.php
<?php

use App\Http\Controllers\FaqController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/page1', function () {
    return view('principal');
});
Route::get('/page2', function () {
    $user=App\Models\users::find(2);
    return dd($user->username);
});
Route::get('/page3', function () {
    return view('third');
})->middleware('auth');
Route::get('/optionalParam/{optional?}', function ($optional='es OPCIONAL') {
   
    return 'la ruta tiene el parametro NO requerido '.$optional;
})->middleware('auth');

Route::resource('faqs','App\Http\Controllers\FaqController');
Route::post('/search_faqs',[App\Http\Controllers\FaqController::class, 'search']);

Route::resource('tags','App\Http\Controllers\TaqController');
Route::post('/search_tags',[App\Http\Controllers\TaqController::class, 'search']);

Route::resource('artists','App\Http\Controllers\ArtistController');
Route::post('/search_artists',[App\Http\Controllers\ArtistController::class, 'search']);

Route::resource('users','App\Http\Controllers\UsersController');
Route::post('/search_users',[App\Http\Controllers\UsersController::class, 'search']);

Route::get('songs/{id}',[App\Http\Controllers\SongController::class, 'index'])->middleware('auth');
Route::post('/search/{id}',[App\Http\Controllers\SongController::class, 'search']);

Route::resource('user_songs','App\Http\Controllers\UserSongController')->middleware('auth');
Route::post('/search_user_songs',[App\Http\Controllers\UserSongController::class, 'search']);

Route::resource('users/{id}/song','App\Http\Controllers\ListSongController')->middleware('auth');
Route::post('/search_songs/{id}',[App\Http\Controllers\ListSongController::class, 'search']);

Route::resource('mails','App\Http\Controllers\MailController');
Route::get('changes_password','App\Http\Controllers\AccountsController@indexPasswordRequest');
Route::post('reset_password_with_token', 'App\Http\Controllers\AccountsController@validatePasswordRequest');
Route::post('update_password','App\Http\Controllers\AccountsController@resetPassword');

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/crud-faq/create-question.blade.php
@extends('templates.template-base')
@section('sub-menu')
    <h2>New QUESTION</h2>
    <ol class="breadcrumb">
   
        <li class="active">
            <strong>Create question</strong>
        </li>
    </ol>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>form to create new question <small>Practica de laravel</small></h5>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" method="POST" action="../faqs">
                        @csrf
                    
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Answer</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('answer') is-invalid @enderror" name="answer" >
                            </div>
                        </div>
                        @error('answer')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Question</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('question') is-invalid @enderror" name="question"  >
                            </div>                           
                        </div>
                        @error('question')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="hr-line-dashed"></div>
                        
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <a href="../../faqs" class="btn btn-white">Cancel</a>
                                <button class="btn btn-primary" type="submit">Save changes</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
  @endsection

resources/views/crud-faq/edit-question.blade.php
@extends('templates.template-base')
@section('sub-menu')
    <h2>Edit</h2>
    <ol class="breadcrumb">
       
        <li class="active">
            <strong>Update Faq</strong>
        </li>
    </ol>
    </div>
@endsection

@section('content')

<div class="row">
  <div class="col-lg-12">
      <div class="ibox float-e-margins">
          <div class="ibox-title">
              <h5>form to update new question <small>Practica de laravel</small></h5>
          </div>
          <div class="ibox-content">
              <form class="form-horizontal" method="POST" action="../{{ $faq->id }}">
                  @csrf
                  @method('PUT')
                  <div class="form-group">
                      <label class="col-sm-2 control-label">Answer</label>
                      <div class="col-sm-10">
                          <input type="text" class="form-control @error('answer') is-invalid @enderror" name="answer" value="{{ $faq->answer}}" >
                      </div>
                  </div>
                  @error('answer')
                      <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  <div class="hr-line-dashed"></div>

                  <div class="form-group">
                      <label class="col-sm-2 control-label">Question</label>
                      <div class="col-sm-10">
                          <input type="text" class="form-control @error('question') is-invalid @enderror" name="question" value="{{ $faq->question}}"  >
                      </div>                           
                  </div>
                  @error('question')
                  <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  <div class="hr-line-dashed"></div>
                  
                  <div class="form-group">
                      <div class="col-sm-4 col-sm-offset-2">
                          <a href="../../faqs" class="btn btn-white">Cancel</a>
                          <button class="btn btn-primary" type="submit">Save changes</button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
  </div>
</div>

@endsection

resources/views/crud-faq/maquet-question.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CRUD</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ ('INSPINIA | Profile 2')}} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>
<body>
    @yield('content-question')
</body>
</html>

resources/views/crud-faq/question.blade.php
@extends('templates.template-base')
@section('sub-menu')
    <h2>F A Q</h2>
    <ol class="breadcrumb">
    
        
        <li class="active">
            <strong>List Faq</strong>
        </li>
    </ol>
    </div>
@endsection
@section('content')



<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of Question</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-plus"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li> <a href="./faqs/create" > create new Question</a>
                            </li>
                        </ul>
                    </div>
                    @if(Session::has('store'))
                    <div class="alert alert-success alert-dismissable">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        <a class="alert-link" href="#">{{Session::get('store')}} </a> successfully saved! .
                    </div>                    
                    @endif
                    @if(Session::has('update'))                    
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <a class="alert-link" href="#">{{Session::get('update')}} </a> successfully updated! .
                        </div>                   
                    @endif
                    @if(Session::has('delete'))                   
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <a class="alert-link" href="#">{{Session::get('delete')}} </a>  deleted correctly! .
                        </div>                                         
                     @endif
                </div>
                <div class="ibox-content">

                    <table class="footable table table-stripped toggle-arrow-tiny">
                        <div class="col-sm-3">
                            <form action="/search_faqs" method="POST" role="search">
                                @csrf
                                <div class="input-group">
                                    <input type="text" placeholder="Search" class="input-sm form-control" name="search"> 
                                    <span class="input-group-btn"><button type="submit" class="btn btn-sm btn-primary"> Go!</button> </span>
                                </div>
                            </form>
                        </div>
                        <thead>
                        <tr>
                            <th data-toggle="true">#</th>
                            <th >Answer</th>
                            <th>Question</th>                           
                            <th>Action</th>                           
                        </tr>
                        </thead>
                        <tbody>
                            @foreach ($table_faqs as $item_faq)
                                <tr>
                                    <td>{{ $loop->index+1 }}</td>
                                    <td>{{ $item_faq->answer}}</td>
                                    <td>{{ $item_faq->question}}</td>
                                
                                    <td><a href="./faqs/{{ $item_faq->id}}/edit" ><i class="fa fa-pencil-square-o"> update</i></a>
                                        
                                        <form method="POST" action="{{ route('faqs.destroy',$item_faq->id) }}">
                                            @csrf
                                            @method('DELETE')
                                        
                                            <button type="submit"  class="fa fa-trash" style="color: red;margin-top:10px;border:none;background-color: transparent;">delete</button>
                                        </form>                                       
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot style="display: none">
                        <tr>
                            <td colspan="5">
                                <ul class="pagination pull-right"></ul>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                    {{ $table_faqs->links() }}
                </div>
            </div>
        </div>
    </div>
</div>  


@endsection